version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: time_away_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=time_away_db
