spring:
  application:
    name: time-away
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
