spring:
  application:
    name: time-away
  datasource:
    url: jdbc:postgresql://localhost:5432/time_away_db
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update