name: tests on push
run-name: ${{ github.actor }} initiate pull-request
on: [push]
jobs:
  Execute-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        run: ./gradlew test
